export default {
  container: {
    width: '67%',
    marginLeft: '3.75em',
    marginBottom: '2em',
  },
  h2: {
    color: '#ffffff',
    fontSize: '2em',
    lineHeight: 1.5,
    letterSpacing: '0.04em',
    margin: '0 0 1.5em 0',
  },
  field1: {
    marginBottom: '1.5em',
    marginRight: '3%',
    display: 'inline-block',
    width: '48%',
  },
  input: {
    background: 'transparent',
    borderColor: 'rgba(255, 255, 255, 0.25)',
    color: '#ffffff',
    height: '3.5em',
    borderRadius: 4,
    border: 'solid 1px',
    display: 'block',
    outline: 0,
    padding: '0 1em',
    textDecoration: 'none',
    width: '100%',
    fontSize: '11pt',
    fontFamily: '"Open Sans", Arial, Helvetica, sans-serif',
    fontWeight: 300,
    lineHeight: 1.75,
    boxSizing: 'border-box',
  },
  field2: {
    marginBottom: '1.5em',
    display: 'inline-block',
    width: '48%',
  },
  field3: {
    marginBottom: '1.5em',
  },
  textarea: {
    padding: '0.75em 1em',
    resize: 'vertical',
    height: 'none',
  },
  actions: {
    cursor: 'default',
    listStype: 'none',
    paddingLeft: 0,
    marginTop: '3em',
  },
  li: {
    paddingRight: 0,
    display: 'inline-block',
    verticalAlign: 'middle',
  },
  button: {
    backgroundColor: 'transparent',
    boxShadow: 'inset 0 0 0 1px rgba(255, 255, 255, 0.75)',
    color: '#ffffff',
    borderRadius: 4,
    transition: 'backgroundColor 0.2s ease-in-out, color 0.2s ease-in-out',
    border: 0,
    cursor: 'pointer',
    display: 'inline-block',
    fontSize: '0.9em',
    fontWeight: 400,
    height: '3.5em',
    letterSpacing: '0.05em',
    lineHeight: '3.5em',
    padding: '0 2em',
    textAlign: 'center',
    textDecoration: 'none',
    textTransform: 'uppercase',
    whiteSpace: 'nowrap',
  },
};
